# Testing
show_gui: False
with_force: False
with_tactile_sensor: False
with_noise: False
visualize_tacto: False
dt: 0.005
reward: "dense"
difficulty: "easy"

model_names:
  - models/GMM/gmm_peg_pose_3.npy
  - models/GMM/gmm_peg_pose_4.npy

defaults:
  - env: sawyer_env
  - test: gmm_test


# Training
K_range: [3, 5]
type: "pose" # "pose" or "force"
demonstration_dir: "demonstrations_txt"
model_name: "models/GMM/gmm_peg"
num_models: 20
