show_gui: False
with_noise: False
with_force: False
visualize_tacto: False
with_tactile_sensor: False
train_episodes: 2000
gmm_model: "optimized_gmm_peg_pose_5.npy"
dt: 0.005

#Test model
model_name: "sac_gmm_best_val.pth"
defaults:
  - agent: sac_agent
  - env: sawyer_env
  - train: sac_train
  - test: sac_test
