show_gui: True
with_noise: False
with_force: False
visualize_tacto: True
train_episodes: 1500

with_tactile_sensor: False
#model_name: "sac_tactile_peg_noise_1090.pth"
model_name: "sac_pose_peg_noise_1500.pth"

defaults:
  - agent: sac_agent
  - env: sawyer_env
  - train: sac_train
  - test: sac_test
