show_gui: False
with_force: False
with_tactile_sensor: True
visualize_tacto: False
model_name: "sac_peg_v2_force_1000.pth"

defaults:
  - agent: sac_agent
  - env: sawyer_env
  - train: sac_train
  - test: sac_test
