show_gui: False
with_noise: False
with_force: False
visualize_tacto: False
with_tactile_sensor: False
dt: 0.005
reward: "dense"
difficulty: "hard"

defaults:
  - hydra/launcher: ray
  - env@worker.env: sawyer_env
  - train@worker.train: sac_worker_train
  - test@worker.validation: sac_worker_validation
