show_gui: False
with_noise: False
with_force: False
visualize_tacto: False
with_tactile_sensor: False
train_episodes: 2000
dt: 0.005
reward: "dense"
difficulty: "hard"

model_name: "sac_peg_easy_tactile_best_val.pth"
#model_name: "sac_pose_peg_noise_1500.pth"

defaults:
  - agent: sac_agent
  - env: sawyer_env
  - train: sac_train
  - test: sac_test
