# Custom
output_dir: "demonstrations/"

show_gui: False
with_force: True
with_tactile_sensor: True
number_demonstrations: 50
dt: 0.005
reward: "dense"
difficulty: "easy"

# Common
with_noise: False
visualize_tacto: False
defaults:
  - env: sawyer_env
